"""Estimated API-equivalent cost for gateway requests.

The gateway's own billing runs on WorkBuddy credits: the `credit` field of a
usage row answers "how much did this request consume from the account". This
module answers a different question - "what would the same tokens have cost at
OpenRouter's listed price" - by pricing every usage row against a snapshot of
OpenRouter's model catalogue (USD per token, the model-level price OpenRouter
publishes rather than the cheapest provider behind it), converted at the
snapshot's usd_cny rate.

Every model is priced from that single source. Most carry one flat price; the
ones OpenRouter prices conditionally carry bands instead - a dearer rate above
an input-length threshold, or a rate that varies with UTC time of day - and the
row's own length and timestamp pick the band. Either way the figure is an
estimate of equivalent token cost, not what the gateway actually billed.

The inline snapshot (same pattern as wb_catalog) is the price the Docker image
ships with; `_fetch_pricing.py` regenerates it, and a `pricing/pricing.json`
next to this script (or the path in WB_PRICING_FILE) overrides the inline copy.
At run time PriceRefresher stores what it fetches as per-model policies keyed by
a hash of their own content, plus a timeline saying which policy each model was
on at any moment. A price that has been seen before is reused rather than written
again, a request records a reference to the policy that priced it, and policies
nothing points at are swept - except a model's live one, the batch just fetched,
and a model's last row of all. All prices are per `unit` tokens (1M) and the
result is CNY; callers divide by meta.usd_cny to show USD.

Only the Python standard library is required.
"""

import bisect
import hashlib
import json
import os
import re
import threading
import time
import urllib.request

# Snapshot generated by _fetch_pricing.py - see that script for the sources
# and the refresh procedure. The inline copy is the fallback every install
# (including the Docker image) has.
_JSON = r'''
{
  "meta": {
    "generated_at": "2026-10-02T01:39:39",
    "base_currency": "CNY",
    "usd_cny": 7.1,
    "sources": {
      "openrouter": "https://openrouter.ai/api/v1/models"
    },
    "note": "单价均为「每百万 token」的美元价，取自 OpenRouter 公布的模型级价（同一模型可能由多家 provider 承接，取它默认路由那家的公布价，不是各家最低价）；按 usd_cny 折算成人民币；按条件定价的模型（输入长度阈值或 UTC 时段）另带 bands，按每条请求的输入长度与时间取档。OpenRouter 的缓存写入价与音频价，本地 usage 日志没有对应的 token 数，未计入。"
  },
  "models": {
    "deepseek-v4.1-flash": {
      "display": "deepseek-v4.1-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4.1-flash",
      "flat": {
        "input_cache_hit": 0.01,
        "input_cache_miss": 0.03,
        "output": 0.5
      }
    },
    "gpt-6-astra": {
      "display": "gpt-6-astra",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-6-astra",
      "flat": {
        "input_cache_hit": 1.0,
        "input_cache_miss": 10.0,
        "output": 50.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 2.0,
            "input_cache_miss": 20.0,
            "output": 75.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "hy4-preview-f": {
      "display": "hy4-preview-f",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview": {
      "display": "hy4-preview",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy3": {
      "display": "hy3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy3",
      "flat": {
        "input_cache_hit": 0.020625,
        "input_cache_miss": 0.0825,
        "output": 0.33
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.033,
            "input_cache_miss": 0.132,
            "output": 0.528
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.020625,
            "input_cache_miss": 0.0825,
            "output": 0.33
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "gpt-5.6-sol": {
      "display": "gpt-5.6-sol",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-sol",
      "flat": {
        "input_cache_hit": 0.2,
        "input_cache_miss": 2.0,
        "output": 10.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.4,
            "input_cache_miss": 4.0,
            "output": 15.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.6-terra": {
      "display": "gpt-5.6-terra",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-terra",
      "flat": {
        "input_cache_hit": 0.2,
        "input_cache_miss": 2.0,
        "output": 12.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.4,
            "input_cache_miss": 4.0,
            "output": 18.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.6-luna": {
      "display": "gpt-5.6-luna",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.6-luna",
      "flat": {
        "input_cache_hit": 0.02,
        "input_cache_miss": 0.2,
        "output": 1.2
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.04,
            "input_cache_miss": 0.4,
            "output": 1.8
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.5": {
      "display": "gpt-5.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.5",
      "flat": {
        "input_cache_hit": 0.5,
        "input_cache_miss": 5.0,
        "output": 30.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 1.0,
            "input_cache_miss": 10.0,
            "output": 45.0
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "gpt-5.4": {
      "display": "gpt-5.4",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.4",
      "flat": {
        "input_cache_hit": 0.25,
        "input_cache_miss": 2.5,
        "output": 15.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.5,
            "input_cache_miss": 5.0,
            "output": 22.5
          },
          "min_prompt_tokens": 272000
        }
      ]
    },
    "grok-4.7": {
      "display": "grok-4.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "x-ai/grok-4.7",
      "flat": {
        "input_cache_hit": 0.5,
        "input_cache_miss": 2.0,
        "output": 6.0
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 1.0,
            "input_cache_miss": 4.0,
            "output": 12.0
          },
          "min_prompt_tokens": 200000
        }
      ]
    },
    "gpt-5.3-codex": {
      "display": "gpt-5.3-codex",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "openai/gpt-5.3-codex",
      "flat": {
        "input_cache_hit": 0.175,
        "input_cache_miss": 1.75,
        "output": 14.0
      }
    },
    "gemini-3.5-flash": {
      "display": "gemini-3.5-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "google/gemini-3.5-flash",
      "flat": {
        "input_cache_hit": 0.15,
        "input_cache_miss": 1.5,
        "output": 9.0
      }
    },
    "glm-5.3": {
      "display": "glm-5.3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.3",
      "flat": {
        "input_cache_hit": 0.192,
        "input_cache_miss": 0.24,
        "output": 3.39
      }
    },
    "glm-5.3-flash": {
      "display": "glm-5.3-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.3-flash",
      "flat": {
        "input_cache_hit": 0.03,
        "input_cache_miss": 0.15,
        "output": 0.5
      }
    },
    "glm-5.2": {
      "display": "glm-5.2",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.2",
      "flat": {
        "input_cache_hit": 0.26,
        "input_cache_miss": 0.41,
        "output": 3.99
      }
    },
    "kimi-k3": {
      "display": "kimi-k3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k3",
      "flat": {
        "input_cache_hit": 0.6635,
        "input_cache_miss": 0.6635,
        "output": 10.0
      }
    },
    "kimi-k2.6": {
      "display": "kimi-k2.6",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.6",
      "flat": {
        "input_cache_hit": 0.07312,
        "input_cache_miss": 0.43415,
        "output": 1.828
      }
    },
    "hy3-x": {
      "display": "hy3-x",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy3",
      "flat": {
        "input_cache_hit": 0.020625,
        "input_cache_miss": 0.0825,
        "output": 0.33
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.033,
            "input_cache_miss": 0.132,
            "output": 0.528
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.020625,
            "input_cache_miss": 0.0825,
            "output": 0.33
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview-dev": {
      "display": "hy4-preview-dev",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "hy4-preview-x": {
      "display": "hy4-preview-x",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hy4-preview",
      "flat": {
        "input_cache_hit": 0.0378,
        "input_cache_miss": 0.7506,
        "output": 2.2509
      },
      "bands": [
        {
          "flat": {
            "input_cache_hit": 0.042,
            "input_cache_miss": 0.834,
            "output": 2.501
          },
          "days": null,
          "start": 0,
          "end": 1600
        },
        {
          "flat": {
            "input_cache_hit": 0.0378,
            "input_cache_miss": 0.7506,
            "output": 2.2509
          },
          "days": null,
          "start": 1600,
          "end": 2400
        }
      ]
    },
    "minimax-m2.5": {
      "display": "minimax-m2.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m2.5",
      "flat": {
        "input_cache_hit": 0.027,
        "input_cache_miss": 0.27,
        "output": 1.08
      }
    },
    "glm-5v-turbo": {
      "display": "glm-5v-turbo",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5v-turbo",
      "flat": {
        "input_cache_hit": 0.24,
        "input_cache_miss": 1.2,
        "output": 4.0
      }
    },
    "glm-5.1": {
      "display": "glm-5.1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5.1",
      "flat": {
        "input_cache_hit": 0.17914,
        "input_cache_miss": 0.9646,
        "output": 3.0316
      }
    },
    "glm-5.0-turbo": {
      "display": "glm-5.0-turbo",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-5-turbo",
      "flat": {
        "input_cache_hit": 0.24,
        "input_cache_miss": 1.2,
        "output": 4.0
      }
    },
    "glm-4.6v": {
      "display": "glm-4.6v",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-4.6v",
      "flat": {
        "input_cache_hit": 0.05,
        "input_cache_miss": 0.3,
        "output": 0.9
      }
    },
    "kimi-k3-1": {
      "display": "kimi-k3-1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k3",
      "flat": {
        "input_cache_hit": 0.6635,
        "input_cache_miss": 0.6635,
        "output": 10.0
      }
    },
    "kimi-k2.7": {
      "display": "kimi-k2.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.7-code",
      "flat": {
        "input_cache_hit": 0.18,
        "input_cache_miss": 0.6712,
        "output": 3.35
      }
    },
    "kimi-k2.5": {
      "display": "kimi-k2.5",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2.5",
      "flat": {
        "input_cache_hit": 0.07,
        "input_cache_miss": 0.45,
        "output": 2.25
      }
    },
    "kimi-k2-thinking": {
      "display": "kimi-k2-thinking",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "moonshotai/kimi-k2-thinking",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.6,
        "output": 2.5
      }
    },
    "minimax-m3": {
      "display": "minimax-m3",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m3",
      "flat": {
        "input_cache_hit": 0.06,
        "input_cache_miss": 0.3,
        "output": 1.2
      }
    },
    "minimax-m2.7": {
      "display": "minimax-m2.7",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "minimax/minimax-m2.7",
      "flat": {
        "input_cache_hit": 0.042,
        "input_cache_miss": 0.21,
        "output": 0.84
      }
    },
    "glm-4.6": {
      "display": "glm-4.6",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "z-ai/glm-4.6",
      "flat": {
        "input_cache_hit": 0.08,
        "input_cache_miss": 0.43,
        "output": 1.75
      }
    },
    "deepseek-v4-flash": {
      "display": "deepseek-v4-flash",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4-flash",
      "flat": {
        "input_cache_hit": 0.008372,
        "input_cache_miss": 0.04186,
        "output": 0.08372
      }
    },
    "deepseek-v4-pro": {
      "display": "deepseek-v4-pro",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v4-pro",
      "flat": {
        "input_cache_hit": 0.0174,
        "input_cache_miss": 0.2088,
        "output": 0.4176
      }
    },
    "deepseek-v3-2-volc": {
      "display": "deepseek-v3-2-volc",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-v3.2",
      "flat": {
        "input_cache_hit": 0.028,
        "input_cache_miss": 0.28,
        "output": 0.42
      }
    },
    "deepseek-v3-1-volc": {
      "display": "deepseek-v3-1-volc",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3.1",
      "flat": {
        "input_cache_hit": 0.13,
        "input_cache_miss": 0.25,
        "output": 0.95
      }
    },
    "deepseek-v3-1": {
      "display": "deepseek-v3-1",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3.1",
      "flat": {
        "input_cache_hit": 0.13,
        "input_cache_miss": 0.25,
        "output": 0.95
      }
    },
    "deepseek-r1-0528": {
      "display": "deepseek-r1-0528",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-r1-0528",
      "flat": {
        "input_cache_hit": 0.35,
        "input_cache_miss": 0.5,
        "output": 2.15
      }
    },
    "deepseek-v3-0324": {
      "display": "deepseek-v3-0324",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "deepseek/deepseek-chat-v3-0324",
      "flat": {
        "input_cache_hit": 0.11,
        "input_cache_miss": 0.29,
        "output": 1.14
      }
    },
    "hunyuan-2.0-instruct": {
      "display": "hunyuan-2.0-instruct",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hunyuan-a13b-instruct",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.14,
        "output": 0.57
      }
    },
    "hunyuan-chat": {
      "display": "hunyuan-chat",
      "source": "openrouter",
      "currency": "USD",
      "unit": 1000000,
      "or_id": "tencent/hunyuan-a13b-instruct",
      "flat": {
        "input_cache_hit": null,
        "input_cache_miss": 0.14,
        "output": 0.57
      }
    }
  }
}
'''

_INLINE = json.loads(_JSON)

_lock = threading.Lock()
_file_cache = {"key": None, "data": None}


def _candidate_file():
    """The out-of-band snapshot path, or None when none is configured."""
    env = os.environ.get("WB_PRICING_FILE")
    if env:
        return env
    here = os.path.dirname(os.path.abspath(__file__))
    path = os.path.join(here, "pricing", "pricing.json")
    return path if os.path.isfile(path) else None


def load_pricing():
    """The active pricing snapshot, reloaded when the file changes.

    The file (when present) wins over the inline copy so an operator can
    drop a refreshed snapshot next to the script without rebuilding; the
    inline copy keeps a broken or missing file from taking pricing down.
    """
    path = _candidate_file()
    key = ("inline", 0)
    if path:
        try:
            key = (path, os.path.getmtime(path))
        except OSError:
            path = None
            key = ("inline", 0)
    with _lock:
        if _file_cache["key"] == key and _file_cache["data"] is not None:
            return _file_cache["data"]
    data = None
    if path:
        try:
            with open(path, encoding="utf-8") as fh:
                loaded = json.load(fh)
            if isinstance(loaded, dict) and isinstance(loaded.get("models"), dict):
                data = loaded
        except Exception:
            data = None
    if data is None:
        data = _INLINE
    with _lock:
        _file_cache.update({"key": key, "data": data})
    return data


def _as_float(value, default=0.0):
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


_WEEKDAYS = ("mon", "tue", "wed", "thu", "fri", "sat", "sun")


def _utc_parts(epoch_sec):
    """(weekday, HHMM) at UTC, the timezone the source states its bands in.

    The gateway can run in a container on UTC and the panel is opened from
    any timezone, so the lookup must not depend on the host clock's zone.
    """
    t = time.gmtime(_as_float(epoch_sec))
    return _WEEKDAYS[t.tm_wday], t.tm_hour * 100 + t.tm_min


def _band_applies(band, prompt_tokens, day, hhmm):
    """Whether a band's condition holds for this row.

    A band carries one of two conditions - a minimum input length, or a UTC
    window; the source never mixes the two within one entry.
    """
    threshold = band.get("min_prompt_tokens")
    if threshold is not None:
        return prompt_tokens >= _as_float(threshold)
    days = band.get("days")
    if days and day not in days:
        return False
    start = _as_float(band.get("start"))
    end = _as_float(band.get("end")) or 2400.0
    return start <= hhmm < end


def band_for(entry, epoch_sec, prompt_tokens=0.0):
    """The rate table for this row, with the band index it came from.

    OpenRouter prices some models conditionally: a dearer rate once the input
    passes a length threshold, or a rate that depends on UTC time of day. The
    bands are kept in the source's order and the *last* one that applies wins.
    The source lists length bands in ascending threshold order, so taking the
    last match picks the tightest one instead of the first that happens to
    fit; the window bands do not overlap, so the same rule holds for them.

    A model without bands, or a row that satisfies none of them, falls back to
    the model's own flat price - the estimate degrades to the single-price
    behaviour rather than to zero. The index is None when that happened.
    """
    bands = entry.get("bands")
    if isinstance(bands, list) and bands:
        day, hhmm = _utc_parts(epoch_sec)
        hit = None
        for index, band in enumerate(bands):
            if not isinstance(band, dict):
                continue
            if not _band_applies(band, prompt_tokens, day, hhmm):
                continue
            table = band.get("flat")
            if isinstance(table, dict):
                hit = (table, index)
        if hit:
            return hit
    table = entry.get("flat")
    return (table if isinstance(table, dict) else {}), None


def _rate_for(entry, epoch_sec, prompt_tokens, meta):
    """The rate table for this row, its band index, and the CNY factor."""
    table, band = band_for(entry, epoch_sec, prompt_tokens)
    factor = 1.0
    if str(entry.get("currency") or "").upper() == "USD":
        factor = _as_float(meta.get("usd_cny"), 1.0) or 1.0
    return table, band, factor


def _pick(rate, key, fallback=None):
    """A per-million rate, falling back to a conservative neighbour.

    A row without a cache-hit price is billed at the miss price (never
    cheaper than the reference engine), so the estimate cannot understate
    the cost.
    """
    value = rate.get(key)
    if value is None and fallback:
        value = rate.get(fallback)
    return _as_float(value)


def compute_row(row, pricing=None):
    """The estimated cost of one usage row, in CNY.

    Returns {"cny": float, "known": bool, "band": int|None}. known=False
    means the model has no price entry - cny stays 0 and the caller reports
    it as unpriced instead of guessing. band is the time-of-day band the
    row's timestamp landed in (None for the model's flat price), so callers
    can tell a time-priced row from an ordinary one.
    """
    if not row:
        return {"cny": 0.0, "known": False, "band": None}
    pricing = pricing if pricing is not None else load_pricing()
    entry = (pricing.get("models") or {}).get(row.get("model"))
    if not isinstance(entry, dict):
        return {"cny": 0.0, "known": False, "band": None}
    meta = pricing.get("meta") or {}
    unit = _as_float(entry.get("unit")) or 1000000.0
    prompt = _as_float(row.get("prompt_tokens"))
    rate, band, factor = _rate_for(entry, row.get("at"), prompt, meta)
    cached = min(_as_float(row.get("cached_tokens")), prompt)
    uncached = prompt - cached
    # The output rate applies to completion_tokens alone: the upstream counts
    # the reasoning tokens inside completion (verified on live and logged rows,
    # see tests/_test_pricing.py), and so does this gateway when it has to
    # estimate a missing usage block. Billing reasoning_tokens on top would
    # charge them twice.
    output = _as_float(row.get("completion_tokens"))
    miss = _pick(rate, "input_cache_miss")
    hit = _pick(rate, "input_cache_hit", "input_cache_miss")
    out_rate = _pick(rate, "output")
    cny = (uncached * miss + cached * hit + output * out_rate) / unit * factor
    return {"cny": cny, "known": True, "band": band}


def sum_rows(rows, pricing=None):
    """Batch totals: {"cny", "priced", "missing"}.

    `missing` is model id -> occurrence count for rows the snapshot cannot
    price, so the panel can point at what is not covered instead of quietly
    under-reporting.
    """
    pricing = pricing if pricing is not None else load_pricing()
    total = 0.0
    priced = 0
    missing = {}
    for row in rows or []:
        cost = compute_row(row, pricing=pricing)
        if cost["known"]:
            total += cost["cny"]
            priced += 1
        else:
            mid = str((row or {}).get("model") or "")
            missing[mid] = missing.get(mid, 0) + 1
    return {"cny": total, "priced": priced, "missing": missing}


def usd_cny():
    """The snapshot's CNY-per-USD rate, for callers that show USD."""
    try:
        return float((load_pricing().get("meta") or {}).get("usd_cny") or 1.0)
    except (TypeError, ValueError):
        return 1.0


# ---- snapshot fetching -------------------------------------------------------
# One code path, shared by the CLI refresher (_fetch_pricing.py) and the
# in-process one below, so the two cannot drift apart.

OPENROUTER_URL = "https://openrouter.ai/api/v1/models"
USD_CNY = 7.10

# Names that differ from OpenRouter's, so the automatic matcher cannot find
# them. Kept deliberately short: a model that matches by name must not be
# listed here, or this becomes the maintenance burden it replaced.
OVERRIDES = {
    # hub 名字比 OpenRouter 多/少一个后缀
    "hy4-preview-f": "tencent/hy4-preview",
    "hy4-preview-dev": "tencent/hy4-preview",
    "hy4-preview-x": "tencent/hy4-preview",
    "hy3-x": "tencent/hy3",
    "kimi-k3-1": "moonshotai/kimi-k3",
    "kimi-k2.7": "moonshotai/kimi-k2.7-code",
    # hub 名字与 OpenRouter 的写法不同（版本号/代号差异）
    "glm-5.0-turbo": "z-ai/glm-5-turbo",
    "deepseek-v3-1": "deepseek/deepseek-chat-v3.1",
    "deepseek-v3-1-volc": "deepseek/deepseek-chat-v3.1",
    "deepseek-v3-2-volc": "deepseek/deepseek-v3.2",
    "deepseek-v3-0324": "deepseek/deepseek-chat-v3-0324",
    # 混元系列在 OpenRouter 上是 a13b-instruct 这一个条目
    "hunyuan-2.0-instruct": "tencent/hunyuan-a13b-instruct",
    "hunyuan-chat": "tencent/hunyuan-a13b-instruct",
}

# OpenRouter 用 UTC 星期名与 HHMM 表达时段档位。
WEEKDAY_KEYS = ("monday", "tuesday", "wednesday", "thursday", "friday",
                "saturday", "sunday")
WEEKDAY_SHORT = ("mon", "tue", "wed", "thu", "fri", "sat", "sun")

_NOTE = ("单价均为「每百万 token」的美元价，取自 OpenRouter 公布的模型级价"
         "（同一模型可能由多家 provider 承接，取它默认路由那家的公布价，"
         "不是各家最低价）；按 usd_cny 折算成人民币；按条件定价的模型"
         "（输入长度阈值或 UTC 时段）另带 bands，按每条请求的输入长度与"
         "时间取档。OpenRouter 的缓存写入价与音频价，本地 usage 日志没有"
         "对应的 token 数，未计入。")


def per_million(value):
    """OpenRouter 的单价是「每 token 的美元」，转成「每百万 token」。"""
    try:
        return round(float(value) * 1_000_000, 6)
    except (TypeError, ValueError):
        return None


def rates_from(item):
    """一条 OpenRouter 记录 → 每百万 token 的三档美元价。"""
    return {
        "input_cache_hit": per_million(item.get("input_cache_read")),
        "input_cache_miss": per_million(item.get("prompt")),
        "output": per_million(item.get("completion")),
    }


def bands_from_overrides(or_entry):
    """条件档位列表；没有条件定价的模型返回空列表。

    OpenRouter 用 overrides 表达两种条件价：

      - min_prompt_tokens：输入长度达到该阈值后改用的价；
      - utc_days / utc_start / utc_end：按时段（UTC）改用的价，
        start / end 是 HHMM 整数（1600 = 16:00），0 作为终点表示当天结束。

    两种条件在源数据里互不混用。档位按源数组的顺序保留，因为计价时取的是
    「最后一条满足条件的档」——这正是源数据的语义：长度档按阈值升序排列
    （实测 32000 → 128000），时段档则互不重叠。与基准价重复、不带任何
    条件的项不取。

    overrides 里还有 input_cache_write / audio / input_audio_cache 这几个
    字段，本地 usage 日志不含对应的 token 数（只有 prompt / completion /
    reasoning / cached），计不出价，所以这里不取。
    """
    out = []
    for item in or_entry.get("overrides") or []:
        if not isinstance(item, dict):
            continue
        band = {"flat": rates_from(item)}
        threshold = item.get("min_prompt_tokens")
        if threshold is not None:
            band["min_prompt_tokens"] = int(threshold)
        elif any(str(k).startswith("utc_") for k in item):
            days = item.get("utc_days")
            picked = [WEEKDAY_SHORT[WEEKDAY_KEYS.index(str(d).lower())]
                      for d in (days if isinstance(days, list) else [])
                      if str(d).lower() in WEEKDAY_KEYS]
            end = item.get("utc_end")
            band.update({
                "days": picked or None,
                "start": int(item.get("utc_start") or 0),
                "end": int(end) if end else 2400,
            })
        else:
            continue
        out.append(band)
    return out


def fetch_openrouter():
    """拉取 OpenRouter 模型列表，返回 {id: pricing}。

    网络失败时抛异常，由调用方决定是记一版失败还是沿用旧价。
    """
    req = urllib.request.Request(
        OPENROUTER_URL, headers={"User-Agent": "workbuddy2api-hub-pricing/1.0"})
    with urllib.request.urlopen(req, timeout=45) as resp:
        payload = json.loads(resp.read().decode("utf-8"))
    return {m.get("id"): (m.get("pricing") or {})
            for m in payload.get("data", [])}


def hub_model_ids():
    """内置目录里的模型 id（国际版在前，保序去重）——取价的输入清单。

    目录里新增模型后，这里就会多一个候选；非 chat 的档位别名（
    default-model 等）在 OpenRouter 里匹配不到，自然落进未定价清单。
    """
    import wb_catalog
    ids, seen = [], set()
    for source in (getattr(wb_catalog, "STATIC_INTL_MODELS", []),
                   getattr(wb_catalog, "STATIC_CN_MODELS", [])):
        for item in source or []:
            mid = str(item.get("id") or "").strip()
            if mid and mid not in seen:
                seen.add(mid)
                ids.append(mid)
    return ids


def normalize(name):
    """名字归一化：小写、去掉所有非字母数字（- . _ 等一律忽略）。"""
    return re.sub(r"[^a-z0-9]", "", str(name or "").lower())


def index_openrouter(or_models):
    """按归一化名字建索引，排除 :batch / :free 等变体。"""
    by_norm = {}
    for mid in or_models or {}:
        if ":" in mid:
            continue
        by_norm.setdefault(normalize(mid.split("/")[-1]), []).append(mid)
    return by_norm


def auto_match(hub_id, by_norm):
    """名字归一化后全等且唯一才返回，否则 None——宁可漏也不错。"""
    cands = by_norm.get(normalize(str(hub_id).split("/")[-1])) or []
    return cands[0] if len(cands) == 1 else None


def resolve(hub_id, or_models, by_norm):
    """(OpenRouter id, 是否来自人工覆盖)；匹配不到返回 (None, False)。"""
    ref = OVERRIDES.get(hub_id)
    if ref and ref in or_models:
        return ref, True
    auto = auto_match(hub_id, by_norm)
    return (auto, False) if auto else (None, False)


def build_snapshot(or_models, previous=None):
    """(doc, unpriced, overridden)。

    or_models 为 None 表示这次抓取失败：结果沿用 previous 里的价（没有就
    留空），这样一次网络抖动不会把价格表清掉。
    """
    by_norm = index_openrouter(or_models) if or_models else {}
    models, unpriced, overridden = {}, [], []
    for hub_id in hub_model_ids():
        if or_models is None:
            old = (previous or {}).get(hub_id)
            if old:
                models[hub_id] = old
            else:
                unpriced.append(hub_id)
            continue
        ref, via_override = resolve(hub_id, or_models, by_norm)
        if not ref:
            unpriced.append(hub_id)
            continue
        if via_override:
            overridden.append(hub_id)
        p = or_models.get(ref) or {}
        entry = {
            "display": hub_id,
            "source": "openrouter",
            "currency": "USD",
            "unit": 1_000_000,
            "or_id": ref,
            "flat": rates_from(p),
        }
        bands = bands_from_overrides(p)
        if bands:
            entry["bands"] = bands
        models[hub_id] = entry
    doc = {
        "meta": {
            "generated_at": time.strftime("%Y-%m-%dT%H:%M:%S"),
            "base_currency": "CNY",
            "usd_cny": USD_CNY,
            "sources": {"openrouter": OPENROUTER_URL},
            "note": _NOTE,
        },
        "models": models,
    }
    return doc, unpriced, overridden


# ---- price policies ----------------------------------------------------------
# A price is stored once per (model, rates) pair, keyed by a hash of its own
# content, and a timeline records which policy each model was on at any moment.
# Re-fetching a price that has been seen before reuses the existing row instead
# of writing a new one, so a vendor flipping A -> B -> A costs two rows rather
# than three. A request stores the *reference* to the policy that priced it, not
# a copy of the rates, which is what lets an unreferenced policy be dropped.

_policy_lock = threading.Lock()
_policies_cache = {"key": None, "data": None}
_timeline_cache = {"key": None, "data": None}
_data_dir_override = None


def data_dir():
    """Where the policy files live: the usage folder by default."""
    if _data_dir_override:
        return _data_dir_override
    env = os.environ.get("WB_PRICING_DIR")
    if env:
        return env
    usage = os.environ.get("WB_PROXY_USAGE_DIR")
    return usage or os.path.join(os.path.dirname(os.path.abspath(__file__)), "usage")


def set_data_dir(path):
    """wb_proxy points this at its own data dir so both sides agree."""
    global _data_dir_override
    with _policy_lock:
        _data_dir_override = path
        _policies_cache.update({"key": None, "data": None})
        _timeline_cache.update({"key": None, "data": None})


def policies_path():
    return os.path.join(data_dir(), "pricing-policies.jsonl")


def timeline_path():
    return os.path.join(data_dir(), "pricing-timeline.jsonl")


def usage_log_path():
    """The usage log, which wb_proxy keeps in the same folder."""
    return os.path.join(data_dir(), "usage.jsonl")


def _file_key(path):
    try:
        return (path, os.path.getmtime(path), os.path.getsize(path))
    except OSError:
        return None


def _read_jsonl(path):
    rows = []
    try:
        with open(path, encoding="utf-8") as fh:
            for line in fh:
                line = line.strip()
                if not line:
                    continue
                try:
                    item = json.loads(line)
                except Exception:
                    continue
                if isinstance(item, dict):
                    rows.append(item)
    except Exception:
        return []
    return rows


def policy_id(model, flat, bands, usd_cny):
    """Content hash: the same model priced the same way gets the same id.

    The rate is part of the hash because it decides the CNY figure just as
    much as the dollar prices do; a rate change is a different policy.
    """
    payload = json.dumps(
        {"model": model, "flat": flat, "bands": bands or None,
         "usd_cny": round(_as_float(usd_cny, 0.0), 6)},
        sort_keys=True, ensure_ascii=False)
    return hashlib.sha1(payload.encode("utf-8")).hexdigest()[:12]


def load_policies():
    """{id: policy} - the policy table, de-duplicated by content."""
    path = policies_path()
    key = _file_key(path)
    if key is None:
        return {}
    with _policy_lock:
        if _policies_cache["key"] == key and _policies_cache["data"] is not None:
            return _policies_cache["data"]
    data = {}
    for row in _read_jsonl(path):
        pid = row.get("id")
        if pid:
            data[pid] = row
    with _policy_lock:
        _policies_cache.update({"key": key, "data": data})
    return data


def load_timeline():
    """[{"at": epoch, "policies": {model: id}}], oldest first."""
    path = timeline_path()
    key = _file_key(path)
    if key is None:
        return []
    with _policy_lock:
        if _timeline_cache["key"] == key and _timeline_cache["data"] is not None:
            return _timeline_cache["data"]
    rows = [r for r in _read_jsonl(path) if isinstance(r.get("policies"), dict)]
    rows.sort(key=lambda r: _as_float(r.get("at")))
    with _policy_lock:
        _timeline_cache.update({"key": key, "data": rows})
    return rows


def current_assignment():
    """(epoch, {model: policy id}) - the timeline's last row, i.e. what is in
    force now. (None, {}) when nothing has been fetched yet.
    """
    timeline = load_timeline()
    if not timeline:
        return None, {}
    last = timeline[-1]
    return _as_float(last.get("at")), dict(last.get("policies") or {})


def current_policy_id(model):
    """The policy in force for this model, for wb_proxy to stamp on a row."""
    _at, assignment = current_assignment()
    return assignment.get(model)


def policy_entry(policy):
    """A policy record turned back into the entry the cost engine expects."""
    entry = {
        "display": policy.get("model"),
        "source": "openrouter",
        "currency": policy.get("currency") or "USD",
        "unit": policy.get("unit") or 1000000,
        "or_id": policy.get("or_id"),
        "flat": policy.get("flat") or {},
    }
    if policy.get("bands"):
        entry["bands"] = policy["bands"]
    return entry


def _doc_for(policy, model):
    return {
        "meta": {"base_currency": "CNY",
                 "usd_cny": _as_float(policy.get("usd_cny"), USD_CNY)},
        "models": {model: policy_entry(policy)},
    }


def record_policies(doc, at=None):
    """Register a fetched snapshot: table first, then the timeline.

    Returns (new policies, timeline appended, {model: id}). A price that is
    already in the table is not written again, and the timeline only grows
    when the assignment actually changes - so a steady price costs nothing per
    refresh no matter how often it is checked.
    """
    stamp = time.time() if at is None else _as_float(at)
    models = doc.get("models") or {}
    usd = _as_float((doc.get("meta") or {}).get("usd_cny"), USD_CNY)
    known = load_policies()
    fresh, assignment = [], {}
    for model, entry in models.items():
        pid = policy_id(model, entry.get("flat"), entry.get("bands"), usd)
        assignment[model] = pid
        if pid in known:
            continue
        known[pid] = {
            "id": pid,
            "model": model,
            "or_id": entry.get("or_id"),
            "currency": entry.get("currency") or "USD",
            "unit": entry.get("unit") or 1000000,
            "usd_cny": usd,
            "flat": entry.get("flat") or {},
            "bands": entry.get("bands"),
            "first_seen": stamp,
        }
        fresh.append(known[pid])
    if fresh:
        path = policies_path()
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with _policy_lock:
            with open(path, "a", encoding="utf-8") as fh:
                for row in fresh:
                    fh.write(json.dumps(row, ensure_ascii=False) + "\n")
            _policies_cache.update({"key": None, "data": None})
    _previous_at, previous = current_assignment()
    changed = False
    if assignment and assignment != previous:
        path = timeline_path()
        os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
        with _policy_lock:
            with open(path, "a", encoding="utf-8") as fh:
                fh.write(json.dumps({"at": stamp, "policies": assignment},
                                    ensure_ascii=False) + "\n")
            _timeline_cache.update({"key": None, "data": None})
        changed = True
    return len(fresh), changed, assignment


def referenced_policy_ids():
    """The policy ids any usage row points at."""
    ids = set()
    try:
        with open(usage_log_path(), encoding="utf-8") as fh:
            for line in fh:
                if '"cost_policy"' not in line:
                    continue
                try:
                    row = json.loads(line)
                except Exception:
                    continue
                pid = row.get("cost_policy")
                if pid:
                    ids.add(pid)
    except Exception:
        return set()
    return ids


def prune_policies(protect=()):
    """Drop the policies nothing points at.

    Kept are the models' current assignment, every id a usage row references,
    whatever the caller pins (the batch just fetched), and - so no model is
    ever left with nothing to price it by - the newest policy of a model that
    would otherwise lose its last row. Returns the removed ids.
    """
    policies = load_policies()
    if not policies:
        return []
    _at, assignment = current_assignment()
    keep = set(assignment.values()) | set(referenced_policy_ids()) | set(protect)
    by_model = {}
    for pid, policy in policies.items():
        by_model.setdefault(policy.get("model"), []).append(pid)
    for ids in by_model.values():
        if any(pid in keep for pid in ids):
            continue
        newest = max(ids, key=lambda p: _as_float((policies[p] or {}).get("first_seen")))
        keep.add(newest)
    removed = [pid for pid in policies if pid not in keep]
    if not removed:
        return []
    path = policies_path()
    tmp = path + ".tmp"
    with _policy_lock:
        with open(tmp, "w", encoding="utf-8") as fh:
            for pid, policy in policies.items():
                if pid in keep:
                    fh.write(json.dumps(policy, ensure_ascii=False) + "\n")
        os.replace(tmp, path)
        _policies_cache.update({"key": None, "data": None})
    return removed


def policy_ref_at(epoch_sec, model):
    """(policy id, backfilled) - which policy a moment in the past should use.

    - the last timeline row at or before the moment, if it lists this model;
    - otherwise the first *later* row that lists it, which is the "the price
      was only learned after the fact" case, marked as backfilled;
    - failing that, an earlier row, also marked, for a model that was dropped;
    - an empty timeline yields (None, False) and the caller falls back to the
      factory snapshot.
    """
    timeline = load_timeline()
    if not timeline:
        return None, False
    stamp = _as_float(epoch_sec)
    index = bisect.bisect_right([_as_float(r.get("at")) for r in timeline], stamp) - 1
    if index < 0:
        index = 0
    rows = timeline[index].get("policies") or {}
    if model in rows:
        return rows[model], False
    for row in timeline:
        if _as_float(row.get("at")) < stamp:
            continue
        hit = (row.get("policies") or {}).get(model)
        if hit:
            return hit, True
    for row in reversed(timeline[:index + 1]):
        hit = (row.get("policies") or {}).get(model)
        if hit:
            return hit, True
    return None, False


def cost_for_row(row):
    """A usage row -> {"cny", "known", "band", "source", "source_at", "backfilled"}.

    The row's own policy reference wins; a row written before references
    existed falls back to the timeline, and a model with no policy at all is
    priced from the factory snapshot. This is the single place that decides
    which price a request is measured against, so the per-row view and every
    summary agree by construction.
    """
    if not row:
        return {"cny": 0.0, "known": False, "band": None, "source": "builtin",
                "source_at": None, "backfilled": False}
    model = row.get("model")
    pid = row.get("cost_policy")
    backfilled = False
    if not pid:
        pid, backfilled = policy_ref_at(row.get("at"), model)
    policy = load_policies().get(pid) if pid else None
    if policy:
        cost = compute_row(row, pricing=_doc_for(policy, model))
        cost["source"] = pid
        cost["source_at"] = _as_float(policy.get("first_seen"))
        cost["backfilled"] = backfilled
        return cost
    cost = compute_row(row, pricing=load_pricing())
    cost["source"] = "builtin"
    cost["source_at"] = None
    cost["backfilled"] = False
    return cost


def policy_label(policy):
    """A policy's wall-clock label (when its price was first seen)."""
    stamp = _as_float((policy or {}).get("first_seen"))
    return time.strftime("%Y-%m-%d %H:%M", time.localtime(stamp)) if stamp else None


# ---- background refresh ------------------------------------------------------
# The gateway refreshes the price history on its own schedule; the interval is
# a panel setting in minutes (0 turns it off). A failed fetch changes nothing,
# so the last good version keeps pricing requests. Prices only move a policy
# when they actually change, so a short interval costs one HTTP GET per cycle
# and nothing else.

DEFAULT_REFRESH_MINUTES = 5


class PriceRefresher(threading.Thread):
    """Periodically append a fresh OpenRouter version to the history."""

    def __init__(self, interval_minutes=DEFAULT_REFRESH_MINUTES):
        super().__init__(daemon=True, name="price-refresher")
        self.interval_minutes = max(0.0, _as_float(interval_minutes))
        self.last_run = None
        self.last_error = None
        self.last_models = 0
        self.next_run = None
        self.logs = []
        self._stop_event = threading.Event()
        self._wake = threading.Event()
        self._run_lock = threading.Lock()

    def log(self, msg):
        stamp = time.strftime("%Y-%m-%d %H:%M:%S")
        self.logs.append("[%s] %s" % (stamp, msg))
        if len(self.logs) > 40:
            self.logs = self.logs[-40:]
        try:
            import wb_proxy
            wb_proxy.add_log_entry("[定价] %s" % msg, tag="pricing")
        except Exception:
            pass

    def interval_seconds(self):
        """The current interval in seconds - the one place the unit is applied."""
        return max(0.0, _as_float(self.interval_minutes)) * 60.0

    def set_interval(self, minutes):
        """Apply a new interval; a running wait picks it up immediately."""
        self.interval_minutes = max(0.0, _as_float(minutes))
        self._wake.set()

    def stop(self):
        self._stop_event.set()
        self._wake.set()

    def run_once(self):
        """抓一次并入账。返回 (ok, message)。"""
        with self._run_lock:
            try:
                or_models = fetch_openrouter()
            except Exception as exc:
                self.last_error = str(exc)
                self.log("抓取失败，继续用上一版价格：%s" % exc)
                return False, str(exc)
            previous = (load_pricing().get("models") or {})
            doc, unpriced, overridden = build_snapshot(or_models, previous)
            if not doc["models"]:
                self.last_error = "抓到了模型列表，但一个都没匹配上"
                self.log(self.last_error)
                return False, self.last_error
            stamp = time.time()
            added, _changed, assignment = record_policies(doc, at=stamp)
            self.last_run = stamp
            self.last_error = None
            self.last_models = len(assignment)
            removed = []
            if added:
                # Only a price never seen before can orphan an older one, so
                # the sweep runs when there is something new - not every cycle.
                removed = prune_policies(protect=set(assignment.values()))
            self.log("已取价：%d 个模型（新增策略 %d，人工覆盖 %d，未定价 %d%s）"
                     % (self.last_models, added, len(overridden), len(unpriced),
                        "，清理无用策略 %d" % len(removed) if removed else ""))
            return True, ""

    def run(self):
        # First boot: with nothing fetched yet, take one reading right away so
        # the panel has something concrete to point at.
        if self.interval_minutes > 0 and not load_timeline():
            try:
                self.run_once()
            except Exception as exc:
                self.log("首次抓取异常：%s" % exc)
        while not self._stop_event.is_set():
            seconds = self.interval_seconds()
            if seconds <= 0:
                self.next_run = None
                self._wake.wait()
                self._wake.clear()
                continue
            self.next_run = time.time() + seconds
            if self._wake.wait(seconds):
                self._wake.clear()
                continue
            if self._stop_event.is_set():
                break
            try:
                self.run_once()
            except Exception as exc:
                self.last_error = str(exc)
                self.log("刷新异常：%s" % exc)

    def status(self):
        policies = load_policies()
        at, assignment = current_assignment()
        return {
            "interval_minutes": self.interval_minutes,
            "enabled": self.interval_minutes > 0,
            "running": self.is_alive(),
            "last_run": self.last_run,
            "last_run_label": (time.strftime("%Y-%m-%d %H:%M",
                                             time.localtime(self.last_run))
                               if self.last_run else None),
            "next_run": self.next_run,
            "next_run_label": (time.strftime("%Y-%m-%d %H:%M",
                                             time.localtime(self.next_run))
                               if self.next_run else None),
            "last_error": self.last_error,
            "last_models": self.last_models,
            "policies": len(policies),
            "models": len(assignment),
            "current_at": at,
            "current_at_label": (time.strftime("%Y-%m-%d %H:%M",
                                               time.localtime(at)) if at else None),
            # What is in force right now, model by model: the declaration the
            # panel shows, and the answer to "which policy is live".
            "current": {m: {"id": pid, "label": policy_label(policies.get(pid) or {})}
                        for m, pid in sorted(assignment.items())},
            "policies_file": policies_path(),
            "timeline": timeline_path(),
            "logs": list(self.logs),
        }
